### ISSUE TITLE
move to python 3?

### ISSUE THREAD

**Issue by sappy5678** [screeps/screeps#118]
python 2 is down after 2020, and node-gyp also supply python 3, maybe we can move to python 3?

**Comment by damianb** [comment]
relevant issue, regarding node-gyp moving to python 3: https://github.com/nodejs/node-gyp/issues/2052

Also, currently the node-gyp readme states that python 3 is now supported. I wonder what version of node-gyp, npm, node are needed then for screeps to say that python 3, not 2, is required.

**Comment by ags131** [comment]
Currently, the only thing (that I know of) holding screeps back is Isolated-vm, the current build does not support python 3, however, a newer build does. I poked the devs about it a few days ago, and they said they would look into it.

**Comment by phanirithvij** [comment]
@ags131 any updates regarding this?

**Comment by ngbrown** [comment]
I was able to install and run the server with just Python 3 installed. I opened pull request #127 to update the readme to that effect.

**Comment by TheLazyLemur** [comment]
As per the final comment on this issue https://github.com/nodejs/node-gyp/issues/1687 python3 does work with gyp.

**Comment by dhharris** [comment]
Ping, looks like merging #127 will close this out.

**Comment by owl-from-hogvarts** [comment]
As i know we already dropped python 2.7 support, so does this mean the issue is solved and can be closed?

**Comment by Regenhardt** [comment]
@artch @o4kapuk seems the work here is all done and just needs someone to merge the PR?

**Comment by TheOverpassArsonist** [comment]
I could be doing something wrong (and probably am) but I'm on EndeavourOS pulling directly from the arch repos and I'm still getting a python 2 based error from what I can tell.

> ~/Screeps> npm install screeps                                                                                                                    
> npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
> npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
> npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
> npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
> npm WARN deprecated acorn-dynamic-import@2.0.2: This is probably built in to whatever tool you're using. If you still need it... idk
> npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
> npm WARN deprecated har-validator@5.1.5: this library is no longer supported
> npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
> npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
> npm WARN deprecated jquery.terminal@0.11.23: Scroll issue in Chrome fixed in version 1.0.5
> npm WARN deprecated angular@1.8.3: For the actively supported Angular, see https://www.npmjs.com/package/@angular/core. AngularJS support has officially ended. For extended AngularJS support options, see https://goo.gle/angularjs-path-forward.
> npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
> npm ERR! code 1
> npm ERR! path /home/username/Screeps/node_modules/@screeps/driver
> npm ERR! command failed
> npm ERR! command sh -c node-gyp rebuild -C native
> npm ERR! gyp info it worked if it ends with ok
> npm ERR! gyp info using node-gyp@3.8.0
> npm ERR! gyp info using node@21.6.1 | linux | x64
> npm ERR! gyp info chdir native
> npm ERR! gyp ERR! configure error 
> npm ERR! gyp ERR! stack Error: Command failed: /usr/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
> npm ERR! gyp ERR! stack   File "<string>", line 1
> npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
> npm ERR! gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> npm ERR! gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
> npm ERR! gyp ERR! stack 
> npm ERR! gyp ERR! stack     at genericNodeError (node:internal/errors:984:15)
> npm ERR! gyp ERR! stack     at wrappedFn (node:internal/errors:538:14)
> npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:422:12)
> npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:519:28)
> npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
> npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
> npm ERR! gyp ERR! System Linux 6.7.1-zen1-1-zen
> npm ERR! gyp ERR! command "/usr/bin/node" "/home/username/Screeps/node_modules/.bin/node-gyp" "rebuild" "-C" "native"
> npm ERR! gyp ERR! cwd /home/username/Screeps/node_modules/@screeps/driver/native
> npm ERR! gyp ERR! node -v v21.6.1
> npm ERR! gyp ERR! node-gyp -v v3.8.0
> npm ERR! gyp ERR! not ok

A non-parenthesis-ed print statement is basically the telltale sign of python 2 and "npm install screeps" is the first thing the readme says to do for launching via CLI. I'm assuming I am missing something here, but I really don't know what. Even going by the [step by step](https://docs.screeps.com/contributed/ps_ubuntu.html) guide it's not obvious that there is anything else needed to get it to install properly. (well, the guide does do some other things first, but most of it is ubuntu specific or about modifications like using mongodb, nothing seems directly related to it not installing with npm install screeps)
